---
- name: Ping dari Juniper ke target
  hosts: JUNIPER
  gather_facts: no

  vars:
    input_schema:
      ping_dest:
        label: "Ping Destination"
        type: string
        required: true
        default: "8.8.8.8"

  tasks:
    - name: Set ping_dest from schema default if missing
      set_fact:
        ping_dest: "{{ ping_dest | default(input_schema.ping_dest.default) }}"

    - name: Jalankan ping ke {{ ping_dest }}
      junipernetworks.junos.junos_command:
        commands:
          - "ping {{ ping_dest }} count 5"
      register: ping_result

    - name: Output result
      debug:
        var: ping_result.stdout_lines
