---
- name: Ping dari Juniper ke target
  hosts: JUNIPER
  gather_facts: no

  vars:
    ping_dest: 

  tasks:
    - name: Jalankan ping ke {{ ping_dest }}
      junipernetworks.junos.junos_command:
        commands:
          - "ping {{ ping_dest }} count 5"
      register: ping_result

    - name: Tampilkan hasil ping
      debug:
        var: ping_result.stdout_lines
