---
- name: Ping dari Juniper ke target
  hosts: JUNIPER
  gather_facts: no

  vars:
    input_schema:
      ping_dest:
        label: "Ping Destination"
        type: string
        
  tasks:
    - name: Jalankan ping ke {{ ping_dest }}
      junipernetworks.junos.junos_command:
        commands:
          - "ping {{ ping_dest | default(input_schema.ping_dest.default) }} count 5"
      register: ping_result

    - debug:
        var: ping_result.stdout_lines
